#!/usr/bin/python
import os
import sys
args = sys.argv
if len(args) < 1:
    print("Please insert proper arguments")
    sys.exit(1)
for i in args[0]:
    if os.path.isdir(i):
        contents = os.listdir(i)
        for f in contents:
            print(os.path.join(i, f))
    else:
